[project]
name = "crono-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bcrypt==4.0.1",
    "fastapi==0.116.1",
    "feedparser==6.0.11",
    "openai>=2.32.0",
    "passlib[bcrypt]>=1.7.4",
    "playwright>=1.58.0",
    "pydantic==2.11.7",
    "python-jose[cryptography]>=3.5.0",
    "readability-lxml>=0.8.4.1",
    "requests>=2.33.1",
    "schedule==1.2.2",
    "uvicorn==0.35.0",
]
